Repository Rater-Inc/frontend-app-v2, pull requests merged in 2025-02, with the labels that each got.

#6 Feat/integrate api
  src/components/CreateSpace/ReviewSpace.tsx
  src/components/Rating/RatingModal.tsx
  src/pages/JoinSpacePage.tsx
  src/pages/RatingPage.tsx
  src/services/api.ts
  src/services/auth.ts
  src/services/space.ts
  src/services/storage.ts
  src/types/types.ts
Labels: bug, enhancement

#20 Create a 404 not found page for unknown routes
  src/App.tsx
  src/pages/NotFoundPage.tsx
Labels: enhancement

#19 Feat/handle api integration
  src/pages/IndividualResultsPage.tsx
  src/pages/OverallResultsPage.tsx
  src/pages/RatingPage.tsx
  src/services/api.ts
  src/services/space.ts
  src/services/storage.ts
  src/types/types.ts
Labels: enhancement

#23 chore : change overal results page back button, navigates to select-a…
  src/pages/OverallResultsPage.tsx
Labels: enhancement

#22 feat : add loader to submit rating
  src/pages/RatingPage.tsx
Labels: enhancement, low

#27 Feat/#12 space name on join space
  src/pages/EnterSpaceIdPage.tsx
  src/pages/JoinSpacePage.tsx
  src/services/api.ts
Labels: enhancement
